settings:
  title: '服务器监控'
  url: 'https://status.eswlnk.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统运行正常'
  notAllmonitorsOperational: '部分系统存在问题'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '优'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: blog-eswlnk-com # unique identifier
    name: Eslwnk Blog
    description: 'Eswlnk 博客' # default=empty
    url: 'https://blog.eswlnk.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: onedrive-eswlnk-com
    name: Eswlnk CloudDisk
    description: 'Eswlnk 网盘'
    url: 'https://onedrive.eswlnk.com/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: bbs-eswlnk-com
    name: 码农社区
    url: 'https://bbs.eswlnk.com/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: blog-a-hacker-com
    name: 码农之家
    url: 'https://blog.a-hacker.com/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
